// Mocks generated by Mockito 5.4.6 from annotations
// in cafe_valdivia/test/services/compra_servicio_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i10;

import 'package:cafe_valdivia/models/compra.dart' as _i11;
import 'package:cafe_valdivia/models/detalle_compra.dart' as _i12;
import 'package:cafe_valdivia/repositorys/compra_repository.dart' as _i6;
import 'package:cafe_valdivia/repositorys/insumo_repository.dart' as _i4;
import 'package:cafe_valdivia/repositorys/inventario_repository.dart' as _i5;
import 'package:cafe_valdivia/repositorys/producto_repository.dart' as _i8;
import 'package:cafe_valdivia/repositorys/proveedor_repository.dart' as _i3;
import 'package:cafe_valdivia/repositorys/venta_repository.dart' as _i7;
import 'package:cafe_valdivia/services/db_helper.dart' as _i2;
import 'package:cafe_valdivia/services/inventario_servicio.dart' as _i13;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i9;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDatabaseHelper_0 extends _i1.SmartFake
    implements _i2.DatabaseHelper {
  _FakeDatabaseHelper_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeProveedorRepository_1 extends _i1.SmartFake
    implements _i3.ProveedorRepository {
  _FakeProveedorRepository_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeInsumosRepository_2 extends _i1.SmartFake
    implements _i4.InsumosRepository {
  _FakeInsumosRepository_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeInventarioRepository_3 extends _i1.SmartFake
    implements _i5.InventarioRepository {
  _FakeInventarioRepository_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCompraRepository_4 extends _i1.SmartFake
    implements _i6.CompraRepository {
  _FakeCompraRepository_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeVentaRepository_5 extends _i1.SmartFake
    implements _i7.VentaRepository {
  _FakeVentaRepository_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeProductoRepository_6 extends _i1.SmartFake
    implements _i8.ProductoRepository {
  _FakeProductoRepository_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [CompraRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCompraRepository extends _i1.Mock implements _i6.CompraRepository {
  MockCompraRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.DatabaseHelper get dbHelper =>
      (super.noSuchMethod(
            Invocation.getter(#dbHelper),
            returnValue: _FakeDatabaseHelper_0(
              this,
              Invocation.getter(#dbHelper),
            ),
          )
          as _i2.DatabaseHelper);

  @override
  String get tableName =>
      (super.noSuchMethod(
            Invocation.getter(#tableName),
            returnValue: _i9.dummyValue<String>(
              this,
              Invocation.getter(#tableName),
            ),
          )
          as String);

  @override
  String get idColumn =>
      (super.noSuchMethod(
            Invocation.getter(#idColumn),
            returnValue: _i9.dummyValue<String>(
              this,
              Invocation.getter(#idColumn),
            ),
          )
          as String);

  @override
  _i3.ProveedorRepository get proveedorRepo =>
      (super.noSuchMethod(
            Invocation.getter(#proveedorRepo),
            returnValue: _FakeProveedorRepository_1(
              this,
              Invocation.getter(#proveedorRepo),
            ),
          )
          as _i3.ProveedorRepository);

  @override
  _i4.InsumosRepository get insumoRepo =>
      (super.noSuchMethod(
            Invocation.getter(#insumoRepo),
            returnValue: _FakeInsumosRepository_2(
              this,
              Invocation.getter(#insumoRepo),
            ),
          )
          as _i4.InsumosRepository);

  @override
  _i10.Future<int> registrarNuevaCompra({
    required _i11.Compra? compra,
    required List<_i12.DetalleCompra>? detallesCompra,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#registrarNuevaCompra, [], {
              #compra: compra,
              #detallesCompra: detallesCompra,
            }),
            returnValue: _i10.Future<int>.value(0),
          )
          as _i10.Future<int>);

  @override
  _i10.Future<Map<String, dynamic>> getFullCompra(int? compraId) =>
      (super.noSuchMethod(
            Invocation.method(#getFullCompra, [compraId]),
            returnValue: _i10.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i10.Future<Map<String, dynamic>>);

  @override
  _i10.Future<List<Map<String, dynamic>>> getAll() =>
      (super.noSuchMethod(
            Invocation.method(#getAll, []),
            returnValue: _i10.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i10.Future<List<Map<String, dynamic>>>);

  @override
  _i10.Future<int> markAsPaid(int? compraId) =>
      (super.noSuchMethod(
            Invocation.method(#markAsPaid, [compraId]),
            returnValue: _i10.Future<int>.value(0),
          )
          as _i10.Future<int>);

  @override
  _i10.Future<int> markAsUnpaid(int? compraId) =>
      (super.noSuchMethod(
            Invocation.method(#markAsUnpaid, [compraId]),
            returnValue: _i10.Future<int>.value(0),
          )
          as _i10.Future<int>);
}

/// A class which mocks [InventarioServicio].
///
/// See the documentation for Mockito's code generation for more information.
class MockInventarioServicio extends _i1.Mock
    implements _i13.InventarioServicio {
  MockInventarioServicio() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.InventarioRepository get inventarioRepository =>
      (super.noSuchMethod(
            Invocation.getter(#inventarioRepository),
            returnValue: _FakeInventarioRepository_3(
              this,
              Invocation.getter(#inventarioRepository),
            ),
          )
          as _i5.InventarioRepository);

  @override
  _i6.CompraRepository get compraRepository =>
      (super.noSuchMethod(
            Invocation.getter(#compraRepository),
            returnValue: _FakeCompraRepository_4(
              this,
              Invocation.getter(#compraRepository),
            ),
          )
          as _i6.CompraRepository);

  @override
  _i7.VentaRepository get ventaRepository =>
      (super.noSuchMethod(
            Invocation.getter(#ventaRepository),
            returnValue: _FakeVentaRepository_5(
              this,
              Invocation.getter(#ventaRepository),
            ),
          )
          as _i7.VentaRepository);

  @override
  _i8.ProductoRepository get productoRepository =>
      (super.noSuchMethod(
            Invocation.getter(#productoRepository),
            returnValue: _FakeProductoRepository_6(
              this,
              Invocation.getter(#productoRepository),
            ),
          )
          as _i8.ProductoRepository);

  @override
  _i2.DatabaseHelper get dbHelper =>
      (super.noSuchMethod(
            Invocation.getter(#dbHelper),
            returnValue: _FakeDatabaseHelper_0(
              this,
              Invocation.getter(#dbHelper),
            ),
          )
          as _i2.DatabaseHelper);

  @override
  _i10.Future<void> resgistrarEntradaPorCompra(int? compraId) =>
      (super.noSuchMethod(
            Invocation.method(#resgistrarEntradaPorCompra, [compraId]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> registrarSalidaPorVenta(int? ventaId) =>
      (super.noSuchMethod(
            Invocation.method(#registrarSalidaPorVenta, [ventaId]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> registrarDevolucionPorVentaAnulada(int? ventaId) =>
      (super.noSuchMethod(
            Invocation.method(#registrarDevolucionPorVentaAnulada, [ventaId]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> registrarAjusteInvetario({
    required int? insumoId,
    required double? cantidad,
    required String? motivo,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#registrarAjusteInvetario, [], {
              #insumoId: insumoId,
              #cantidad: cantidad,
              #motivo: motivo,
            }),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<bool> verificarStockDisponible(int? productoId, int? cantidad) =>
      (super.noSuchMethod(
            Invocation.method(#verificarStockDisponible, [
              productoId,
              cantidad,
            ]),
            returnValue: _i10.Future<bool>.value(false),
          )
          as _i10.Future<bool>);

  @override
  _i10.Future<double> calcularCostoProducto(int? productoId) =>
      (super.noSuchMethod(
            Invocation.method(#calcularCostoProducto, [productoId]),
            returnValue: _i10.Future<double>.value(0.0),
          )
          as _i10.Future<double>);
}
