// Mocks generated by Mockito 5.4.6 from annotations
// in cafe_valdivia/test/services/compra_servicio_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;

import 'package:cafe_valdivia/core/models/compra.dart' as _i5;
import 'package:cafe_valdivia/core/models/detalle_compra.dart' as _i9;
import 'package:cafe_valdivia/repositorys/compra_repository.dart' as _i6;
import 'package:cafe_valdivia/repositorys/articulo_repository.dart' as _i4;
import 'package:cafe_valdivia/repositorys/proveedor_repository.dart' as _i3;
import 'package:cafe_valdivia/services/db_helper.dart' as _i2;
import 'package:cafe_valdivia/services/inventario_servicio.dart' as _i10;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeDatabaseHelper_0 extends _i1.SmartFake
    implements _i2.DatabaseHelper {
  _FakeDatabaseHelper_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeProveedorRepository_1 extends _i1.SmartFake
    implements _i3.ProveedorRepository {
  _FakeProveedorRepository_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeArticuloRepository_2 extends _i1.SmartFake
    implements _i4.ArticuloRepository {
  _FakeArticuloRepository_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCompra_3 extends _i1.SmartFake implements _i5.Compra {
  _FakeCompra_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [CompraRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCompraRepository extends _i1.Mock implements _i6.CompraRepository {
  MockCompraRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.DatabaseHelper get dbHelper =>
      (super.noSuchMethod(
            Invocation.getter(#dbHelper),
            returnValue: _FakeDatabaseHelper_0(
              this,
              Invocation.getter(#dbHelper),
            ),
          )
          as _i2.DatabaseHelper);

  @override
  String get tableName =>
      (super.noSuchMethod(
            Invocation.getter(#tableName),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#tableName),
            ),
          )
          as String);

  @override
  String get idColumn =>
      (super.noSuchMethod(
            Invocation.getter(#idColumn),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#idColumn),
            ),
          )
          as String);

  @override
  _i3.ProveedorRepository get proveedorRepo =>
      (super.noSuchMethod(
            Invocation.getter(#proveedorRepo),
            returnValue: _FakeProveedorRepository_1(
              this,
              Invocation.getter(#proveedorRepo),
            ),
          )
          as _i3.ProveedorRepository);

  @override
  _i4.ArticuloRepository get articuloRepo =>
      (super.noSuchMethod(
            Invocation.getter(#articuloRepo),
            returnValue: _FakeArticuloRepository_2(
              this,
              Invocation.getter(#articuloRepo),
            ),
          )
          as _i4.ArticuloRepository);

  @override
  _i5.Compra fromJson(Map<String, dynamic>? map) =>
      (super.noSuchMethod(
            Invocation.method(#fromJson, [map]),
            returnValue: _FakeCompra_3(
              this,
              Invocation.method(#fromJson, [map]),
            ),
          )
          as _i5.Compra);

  @override
  Map<String, dynamic> toJson(_i5.Compra? entity) =>
      (super.noSuchMethod(
            Invocation.method(#toJson, [entity]),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  _i8.Future<int> create(_i5.Compra? entity) =>
      (super.noSuchMethod(
            Invocation.method(#create, [entity]),
            returnValue: _i8.Future<int>.value(0),
          )
          as _i8.Future<int>);

  @override
  _i8.Future<int> delete(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [id]),
            returnValue: _i8.Future<int>.value(0),
          )
          as _i8.Future<int>);

  @override
  _i8.Future<List<_i5.Compra>> getAll({
    String? where,
    List<Object?>? whereArgs,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getAll, [], {
              #where: where,
              #whereArgs: whereArgs,
            }),
            returnValue: _i8.Future<List<_i5.Compra>>.value(<_i5.Compra>[]),
          )
          as _i8.Future<List<_i5.Compra>>);

  @override
  _i8.Future<_i5.Compra> getById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getById, [id]),
            returnValue: _i8.Future<_i5.Compra>.value(
              _FakeCompra_3(this, Invocation.method(#getById, [id])),
            ),
          )
          as _i8.Future<_i5.Compra>);

  @override
  _i8.Future<int> update(_i5.Compra? entity) =>
      (super.noSuchMethod(
            Invocation.method(#update, [entity]),
            returnValue: _i8.Future<int>.value(0),
          )
          as _i8.Future<int>);

  @override
  _i8.Future<int> registrarNuevaCompra({
    required _i5.Compra? compra,
    required List<_i9.DetalleCompra>? detallesCompra,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#registrarNuevaCompra, [], {
              #compra: compra,
              #detallesCompra: detallesCompra,
            }),
            returnValue: _i8.Future<int>.value(0),
          )
          as _i8.Future<int>);

  @override
  _i8.Future<Map<String, dynamic>> getFullCompra(int? compraId) =>
      (super.noSuchMethod(
            Invocation.method(#getFullCompra, [compraId]),
            returnValue: _i8.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i8.Future<Map<String, dynamic>>);

  @override
  _i8.Future<List<Map<String, dynamic>>> getAllDetalles() =>
      (super.noSuchMethod(
            Invocation.method(#getAllDetalles, []),
            returnValue: _i8.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i8.Future<List<Map<String, dynamic>>>);

  @override
  _i8.Future<List<_i5.Compra>> getAllOnlyCompra({
    String? where,
    List<Object?>? whereArgs,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getAllOnlyCompra, [], {
              #where: where,
              #whereArgs: whereArgs,
            }),
            returnValue: _i8.Future<List<_i5.Compra>>.value(<_i5.Compra>[]),
          )
          as _i8.Future<List<_i5.Compra>>);

  @override
  _i8.Future<int> markAsPaid(int? compraId) =>
      (super.noSuchMethod(
            Invocation.method(#markAsPaid, [compraId]),
            returnValue: _i8.Future<int>.value(0),
          )
          as _i8.Future<int>);

  @override
  _i8.Future<int> markAsUnpaid(int? compraId) =>
      (super.noSuchMethod(
            Invocation.method(#markAsUnpaid, [compraId]),
            returnValue: _i8.Future<int>.value(0),
          )
          as _i8.Future<int>);

  @override
  _i8.Future<List<Map<String, dynamic>>> getAllNombreProveedor({
    String? where,
    List<Object?>? whereArgs,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getAllNombreProveedor, [], {
              #where: where,
              #whereArgs: whereArgs,
            }),
            returnValue: _i8.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i8.Future<List<Map<String, dynamic>>>);
}

/// A class which mocks [InventarioServicio].
///
/// See the documentation for Mockito's code generation for more information.
class MockInventarioServicio extends _i1.Mock
    implements _i10.InventarioServicio {
  MockInventarioServicio() {
    _i1.throwOnMissingStub(this);
  }
}
