// Mocks generated by Mockito 5.4.6 from annotations
// in cafe_valdivia/test/services/inventario_servicio_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i11;

import 'package:cafe_valdivia/core/models/compra.dart' as _i7;
import 'package:cafe_valdivia/core/models/detalle_compra.dart' as _i15;
import 'package:cafe_valdivia/core/models/detalle_venta.dart' as _i18;
import 'package:cafe_valdivia/core/models/unidad_medida.dart' as _i4;
import 'package:cafe_valdivia/core/models/venta.dart' as _i17;
import 'package:cafe_valdivia/repositorys/cliente_repository.dart' as _i8;
import 'package:cafe_valdivia/repositorys/compra_repository.dart' as _i14;
import 'package:cafe_valdivia/repositorys/articulo_repository.dart' as _i6;
import 'package:cafe_valdivia/repositorys/inventario_repository.dart' as _i12;
import 'package:cafe_valdivia/repositorys/producto_repository.dart' as _i9;
import 'package:cafe_valdivia/repositorys/proveedor_repository.dart' as _i5;
import 'package:cafe_valdivia/repositorys/unidad_medida_repository.dart' as _i3;
import 'package:cafe_valdivia/repositorys/venta_repository.dart' as _i16;
import 'package:cafe_valdivia/services/db_helper.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i13;
import 'package:sqflite/sqflite.dart' as _i10;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeDatabaseHelper_0 extends _i1.SmartFake
    implements _i2.DatabaseHelper {
  _FakeDatabaseHelper_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUnidadMedidaRepository_1 extends _i1.SmartFake
    implements _i3.UnidadMedidaRepository {
  _FakeUnidadMedidaRepository_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUnidadMedida_2 extends _i1.SmartFake implements _i4.UnidadMedida {
  _FakeUnidadMedida_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeProveedorRepository_3 extends _i1.SmartFake
    implements _i5.ProveedorRepository {
  _FakeProveedorRepository_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeArticuloRepository_4 extends _i1.SmartFake
    implements _i6.ArticuloRepository {
  _FakeArticuloRepository_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCompra_5 extends _i1.SmartFake implements _i7.Compra {
  _FakeCompra_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeClienteRepository_6 extends _i1.SmartFake
    implements _i8.ClienteRepository {
  _FakeClienteRepository_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeProductoRepository_7 extends _i1.SmartFake
    implements _i9.ProductoRepository {
  _FakeProductoRepository_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDatabase_8 extends _i1.SmartFake implements _i10.Database {
  _FakeDatabase_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFuture_9<T1> extends _i1.SmartFake implements _i11.Future<T1> {
  _FakeFuture_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [InventarioRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockInventarioRepository extends _i1.Mock
    implements _i12.InventarioRepository {
  MockInventarioRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.DatabaseHelper get dbHelper =>
      (super.noSuchMethod(
            Invocation.getter(#dbHelper),
            returnValue: _FakeDatabaseHelper_0(
              this,
              Invocation.getter(#dbHelper),
            ),
          )
          as _i2.DatabaseHelper);

  @override
  _i11.Future<double> getStockArticulo({required int? articuloId}) =>
      (super.noSuchMethod(
            Invocation.method(#getStockArticulo, [], {#articuloId: articuloId}),
            returnValue: _i11.Future<double>.value(0.0),
          )
          as _i11.Future<double>);

  @override
  _i11.Future<double> getStockProducto({required int? idProducto}) =>
      (super.noSuchMethod(
            Invocation.method(#getStockProducto, [], {#idProducto: idProducto}),
            returnValue: _i11.Future<double>.value(0.0),
          )
          as _i11.Future<double>);

  @override
  _i11.Future<List<Map<String, dynamic>>> getMovimientoArticuloDetallado({
    int? idArticulo,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getMovimientoArticuloDetallado, [], {
              #idArticulo: idArticulo,
            }),
            returnValue: _i11.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i11.Future<List<Map<String, dynamic>>>);

  @override
  _i11.Future<List<Map<String, dynamic>>> getMovimientoProductoDetallado({
    int? idProducto,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getMovimientoProductoDetallado, [], {
              #idProducto: idProducto,
            }),
            returnValue: _i11.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i11.Future<List<Map<String, dynamic>>>);
}

/// A class which mocks [ArticuloRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockArticuloRepository extends _i1.Mock implements _i6.ArticuloRepository {
  MockArticuloRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.DatabaseHelper get dbHelper =>
      (super.noSuchMethod(
            Invocation.getter(#dbHelper),
            returnValue: _FakeDatabaseHelper_0(
              this,
              Invocation.getter(#dbHelper),
            ),
          )
          as _i2.DatabaseHelper);

  @override
  String get tableName =>
      (super.noSuchMethod(
            Invocation.getter(#tableName),
            returnValue: _i13.dummyValue<String>(
              this,
              Invocation.getter(#tableName),
            ),
          )
          as String);

  @override
  String get idColumn =>
      (super.noSuchMethod(
            Invocation.getter(#idColumn),
            returnValue: _i13.dummyValue<String>(
              this,
              Invocation.getter(#idColumn),
            ),
          )
          as String);

  @override
  _i3.UnidadMedidaRepository get unidadRepo =>
      (super.noSuchMethod(
            Invocation.getter(#unidadRepo),
            returnValue: _FakeUnidadMedidaRepository_1(
              this,
              Invocation.getter(#unidadRepo),
            ),
          )
          as _i3.UnidadMedidaRepository);

  @override
  dynamic fromJson(Map<String, dynamic>? map) =>
      super.noSuchMethod(Invocation.method(#fromJson, [map]));

  @override
  Map<String, dynamic> toJson(dynamic entity) =>
      (super.noSuchMethod(
            Invocation.method(#toJson, [entity]),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  _i11.Future<int> create(dynamic entity) =>
      (super.noSuchMethod(
            Invocation.method(#create, [entity]),
            returnValue: _i11.Future<int>.value(0),
          )
          as _i11.Future<int>);

  @override
  _i11.Future<int> delete(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [id]),
            returnValue: _i11.Future<int>.value(0),
          )
          as _i11.Future<int>);

  @override
  _i11.Future<List<dynamic>> getAll({
    String? where,
    List<Object?>? whereArgs,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getAll, [], {
              #where: where,
              #whereArgs: whereArgs,
            }),
            returnValue: _i11.Future<List<dynamic>>.value(<dynamic>[]),
          )
          as _i11.Future<List<dynamic>>);

  @override
  _i11.Future<dynamic> getById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getById, [id]),
            returnValue: _i11.Future<dynamic>.value(),
          )
          as _i11.Future<dynamic>);

  @override
  _i11.Future<int> update(dynamic entity) =>
      (super.noSuchMethod(
            Invocation.method(#update, [entity]),
            returnValue: _i11.Future<int>.value(0),
          )
          as _i11.Future<int>);

  @override
  _i11.Future<(_i4.UnidadMedida, List<dynamic>)> getArticuloByIdUnidad({
    required int? idUnidad,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getArticuloByIdUnidad, [], {#idUnidad: idUnidad}),
            returnValue: _i11.Future<(_i4.UnidadMedida, List<dynamic>)>.value((
              _FakeUnidadMedida_2(
                this,
                Invocation.method(#getArticuloByIdUnidad, [], {
                  #idUnidad: idUnidad,
                }),
              ),
              <dynamic>[],
            )),
          )
          as _i11.Future<(_i4.UnidadMedida, List<dynamic>)>);

  @override
  _i11.Future<double> getCostoPromedio(int? articuloId) =>
      (super.noSuchMethod(
            Invocation.method(#getCostoPromedio, [articuloId]),
            returnValue: _i11.Future<double>.value(0.0),
          )
          as _i11.Future<double>);

  @override
  _i11.Future<List<dynamic>> search(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#search, [query]),
            returnValue: _i11.Future<List<dynamic>>.value(<dynamic>[]),
          )
          as _i11.Future<List<dynamic>>);
}

/// A class which mocks [CompraRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCompraRepository extends _i1.Mock implements _i14.CompraRepository {
  MockCompraRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.DatabaseHelper get dbHelper =>
      (super.noSuchMethod(
            Invocation.getter(#dbHelper),
            returnValue: _FakeDatabaseHelper_0(
              this,
              Invocation.getter(#dbHelper),
            ),
          )
          as _i2.DatabaseHelper);

  @override
  String get tableName =>
      (super.noSuchMethod(
            Invocation.getter(#tableName),
            returnValue: _i13.dummyValue<String>(
              this,
              Invocation.getter(#tableName),
            ),
          )
          as String);

  @override
  String get idColumn =>
      (super.noSuchMethod(
            Invocation.getter(#idColumn),
            returnValue: _i13.dummyValue<String>(
              this,
              Invocation.getter(#idColumn),
            ),
          )
          as String);

  @override
  _i5.ProveedorRepository get proveedorRepo =>
      (super.noSuchMethod(
            Invocation.getter(#proveedorRepo),
            returnValue: _FakeProveedorRepository_3(
              this,
              Invocation.getter(#proveedorRepo),
            ),
          )
          as _i5.ProveedorRepository);

  @override
  _i6.ArticuloRepository get articuloRepo =>
      (super.noSuchMethod(
            Invocation.getter(#articuloRepo),
            returnValue: _FakeArticuloRepository_4(
              this,
              Invocation.getter(#articuloRepo),
            ),
          )
          as _i6.ArticuloRepository);

  @override
  _i7.Compra fromJson(Map<String, dynamic>? map) =>
      (super.noSuchMethod(
            Invocation.method(#fromJson, [map]),
            returnValue: _FakeCompra_5(
              this,
              Invocation.method(#fromJson, [map]),
            ),
          )
          as _i7.Compra);

  @override
  Map<String, dynamic> toJson(_i7.Compra? entity) =>
      (super.noSuchMethod(
            Invocation.method(#toJson, [entity]),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  _i11.Future<int> create(_i7.Compra? entity) =>
      (super.noSuchMethod(
            Invocation.method(#create, [entity]),
            returnValue: _i11.Future<int>.value(0),
          )
          as _i11.Future<int>);

  @override
  _i11.Future<int> delete(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [id]),
            returnValue: _i11.Future<int>.value(0),
          )
          as _i11.Future<int>);

  @override
  _i11.Future<List<_i7.Compra>> getAll({
    String? where,
    List<Object?>? whereArgs,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getAll, [], {
              #where: where,
              #whereArgs: whereArgs,
            }),
            returnValue: _i11.Future<List<_i7.Compra>>.value(<_i7.Compra>[]),
          )
          as _i11.Future<List<_i7.Compra>>);

  @override
  _i11.Future<_i7.Compra> getById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getById, [id]),
            returnValue: _i11.Future<_i7.Compra>.value(
              _FakeCompra_5(this, Invocation.method(#getById, [id])),
            ),
          )
          as _i11.Future<_i7.Compra>);

  @override
  _i11.Future<int> update(_i7.Compra? entity) =>
      (super.noSuchMethod(
            Invocation.method(#update, [entity]),
            returnValue: _i11.Future<int>.value(0),
          )
          as _i11.Future<int>);

  @override
  _i11.Future<int> registrarNuevaCompra({
    required _i7.Compra? compra,
    required List<_i15.DetalleCompra>? detallesCompra,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#registrarNuevaCompra, [], {
              #compra: compra,
              #detallesCompra: detallesCompra,
            }),
            returnValue: _i11.Future<int>.value(0),
          )
          as _i11.Future<int>);

  @override
  _i11.Future<Map<String, dynamic>> getFullCompra(int? compraId) =>
      (super.noSuchMethod(
            Invocation.method(#getFullCompra, [compraId]),
            returnValue: _i11.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i11.Future<Map<String, dynamic>>);

  @override
  _i11.Future<List<Map<String, dynamic>>> getAllDetalles() =>
      (super.noSuchMethod(
            Invocation.method(#getAllDetalles, []),
            returnValue: _i11.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i11.Future<List<Map<String, dynamic>>>);

  @override
  _i11.Future<List<_i7.Compra>> getAllOnlyCompra({
    String? where,
    List<Object?>? whereArgs,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getAllOnlyCompra, [], {
              #where: where,
              #whereArgs: whereArgs,
            }),
            returnValue: _i11.Future<List<_i7.Compra>>.value(<_i7.Compra>[]),
          )
          as _i11.Future<List<_i7.Compra>>);

  @override
  _i11.Future<int> markAsPaid(int? compraId) =>
      (super.noSuchMethod(
            Invocation.method(#markAsPaid, [compraId]),
            returnValue: _i11.Future<int>.value(0),
          )
          as _i11.Future<int>);

  @override
  _i11.Future<int> markAsUnpaid(int? compraId) =>
      (super.noSuchMethod(
            Invocation.method(#markAsUnpaid, [compraId]),
            returnValue: _i11.Future<int>.value(0),
          )
          as _i11.Future<int>);

  @override
  _i11.Future<List<Map<String, dynamic>>> getAllNombreProveedor({
    String? where,
    List<Object?>? whereArgs,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getAllNombreProveedor, [], {
              #where: where,
              #whereArgs: whereArgs,
            }),
            returnValue: _i11.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i11.Future<List<Map<String, dynamic>>>);
}

/// A class which mocks [VentaRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockVentaRepository extends _i1.Mock implements _i16.VentaRepository {
  MockVentaRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.DatabaseHelper get dbHelper =>
      (super.noSuchMethod(
            Invocation.getter(#dbHelper),
            returnValue: _FakeDatabaseHelper_0(
              this,
              Invocation.getter(#dbHelper),
            ),
          )
          as _i2.DatabaseHelper);

  @override
  String get tableName =>
      (super.noSuchMethod(
            Invocation.getter(#tableName),
            returnValue: _i13.dummyValue<String>(
              this,
              Invocation.getter(#tableName),
            ),
          )
          as String);

  @override
  String get idColumn =>
      (super.noSuchMethod(
            Invocation.getter(#idColumn),
            returnValue: _i13.dummyValue<String>(
              this,
              Invocation.getter(#idColumn),
            ),
          )
          as String);

  @override
  _i8.ClienteRepository get clienteRepo =>
      (super.noSuchMethod(
            Invocation.getter(#clienteRepo),
            returnValue: _FakeClienteRepository_6(
              this,
              Invocation.getter(#clienteRepo),
            ),
          )
          as _i8.ClienteRepository);

  @override
  _i9.ProductoRepository get productoRepo =>
      (super.noSuchMethod(
            Invocation.getter(#productoRepo),
            returnValue: _FakeProductoRepository_7(
              this,
              Invocation.getter(#productoRepo),
            ),
          )
          as _i9.ProductoRepository);

  @override
  _i11.Future<int> registrarNuevaVenta({
    required _i17.Venta? venta,
    required List<_i18.DetalleVenta>? detallesVenta,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#registrarNuevaVenta, [], {
              #venta: venta,
              #detallesVenta: detallesVenta,
            }),
            returnValue: _i11.Future<int>.value(0),
          )
          as _i11.Future<int>);

  @override
  _i11.Future<Map<String, dynamic>> getFullVenta({required int? ventaId}) =>
      (super.noSuchMethod(
            Invocation.method(#getFullVenta, [], {#ventaId: ventaId}),
            returnValue: _i11.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i11.Future<Map<String, dynamic>>);

  @override
  _i11.Future<List<Map<String, dynamic>>> getAll() =>
      (super.noSuchMethod(
            Invocation.method(#getAll, []),
            returnValue: _i11.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i11.Future<List<Map<String, dynamic>>>);

  @override
  _i11.Future<int> markAsPaid(int? ventaId) =>
      (super.noSuchMethod(
            Invocation.method(#markAsPaid, [ventaId]),
            returnValue: _i11.Future<int>.value(0),
          )
          as _i11.Future<int>);

  @override
  _i11.Future<int> markAsUnpaid(int? ventaId) =>
      (super.noSuchMethod(
            Invocation.method(#markAsUnpaid, [ventaId]),
            returnValue: _i11.Future<int>.value(0),
          )
          as _i11.Future<int>);

  @override
  _i11.Future<int> markAsNulled(int? ventaId) =>
      (super.noSuchMethod(
            Invocation.method(#markAsNulled, [ventaId]),
            returnValue: _i11.Future<int>.value(0),
          )
          as _i11.Future<int>);
}

/// A class which mocks [ProductoRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockProductoRepository extends _i1.Mock
    implements _i9.ProductoRepository {
  MockProductoRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.DatabaseHelper get dbHelper =>
      (super.noSuchMethod(
            Invocation.getter(#dbHelper),
            returnValue: _FakeDatabaseHelper_0(
              this,
              Invocation.getter(#dbHelper),
            ),
          )
          as _i2.DatabaseHelper);

  @override
  String get tableName =>
      (super.noSuchMethod(
            Invocation.getter(#tableName),
            returnValue: _i13.dummyValue<String>(
              this,
              Invocation.getter(#tableName),
            ),
          )
          as String);

  @override
  String get idColumn =>
      (super.noSuchMethod(
            Invocation.getter(#idColumn),
            returnValue: _i13.dummyValue<String>(
              this,
              Invocation.getter(#idColumn),
            ),
          )
          as String);

  @override
  _i6.ArticuloRepository get articuloRepo =>
      (super.noSuchMethod(
            Invocation.getter(#articuloRepo),
            returnValue: _FakeArticuloRepository_4(
              this,
              Invocation.getter(#articuloRepo),
            ),
          )
          as _i6.ArticuloRepository);

  @override
  dynamic fromJson(Map<String, dynamic>? map) =>
      super.noSuchMethod(Invocation.method(#fromJson, [map]));

  @override
  Map<String, dynamic> toJson(dynamic entity) =>
      (super.noSuchMethod(
            Invocation.method(#toJson, [entity]),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  _i11.Future<int> create(dynamic entity) =>
      (super.noSuchMethod(
            Invocation.method(#create, [entity]),
            returnValue: _i11.Future<int>.value(0),
          )
          as _i11.Future<int>);

  @override
  _i11.Future<int> delete(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [id]),
            returnValue: _i11.Future<int>.value(0),
          )
          as _i11.Future<int>);

  @override
  _i11.Future<List<dynamic>> getAll({
    String? where,
    List<Object?>? whereArgs,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getAll, [], {
              #where: where,
              #whereArgs: whereArgs,
            }),
            returnValue: _i11.Future<List<dynamic>>.value(<dynamic>[]),
          )
          as _i11.Future<List<dynamic>>);

  @override
  _i11.Future<dynamic> getById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getById, [id]),
            returnValue: _i11.Future<dynamic>.value(),
          )
          as _i11.Future<dynamic>);

  @override
  _i11.Future<int> update(dynamic entity) =>
      (super.noSuchMethod(
            Invocation.method(#update, [entity]),
            returnValue: _i11.Future<int>.value(0),
          )
          as _i11.Future<int>);

  @override
  _i11.Future<(dynamic, List<dynamic>)> getProductoByArticuloId({
    required int? idArticulo,
    int? idProducto,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getProductoByArticuloId, [], {
              #idArticulo: idArticulo,
              #idProducto: idProducto,
            }),
            returnValue: _i11.Future<(dynamic, List<dynamic>)>.value((
              null,
              <dynamic>[],
            )),
          )
          as _i11.Future<(dynamic, List<dynamic>)>);
}

/// A class which mocks [DatabaseHelper].
///
/// See the documentation for Mockito's code generation for more information.
class MockDatabaseHelper extends _i1.Mock implements _i2.DatabaseHelper {
  MockDatabaseHelper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i11.Future<_i10.Database> get database =>
      (super.noSuchMethod(
            Invocation.getter(#database),
            returnValue: _i11.Future<_i10.Database>.value(
              _FakeDatabase_8(this, Invocation.getter(#database)),
            ),
          )
          as _i11.Future<_i10.Database>);

  @override
  _i11.Future<void> testOnCreate(_i10.Database? db, [int? version = 5]) =>
      (super.noSuchMethod(
            Invocation.method(#testOnCreate, [db, version]),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<void> testOnConfigure(_i10.Database? db) =>
      (super.noSuchMethod(
            Invocation.method(#testOnConfigure, [db]),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  void setMockDatabase(_i10.Database? database) => super.noSuchMethod(
    Invocation.method(#setMockDatabase, [database]),
    returnValueForMissingStub: null,
  );

  @override
  _i11.Future<int> insert(String? table, Map<String, dynamic>? data) =>
      (super.noSuchMethod(
            Invocation.method(#insert, [table, data]),
            returnValue: _i11.Future<int>.value(0),
          )
          as _i11.Future<int>);

  @override
  _i11.Future<List<Map<String, dynamic>>> query(
    String? table, {
    bool? distinct,
    List<String>? columns,
    String? where,
    List<Object?>? whereArgs,
    String? groupBy,
    String? having,
    String? orderBy,
    int? limit,
    int? offset,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #query,
              [table],
              {
                #distinct: distinct,
                #columns: columns,
                #where: where,
                #whereArgs: whereArgs,
                #groupBy: groupBy,
                #having: having,
                #orderBy: orderBy,
                #limit: limit,
                #offset: offset,
              },
            ),
            returnValue: _i11.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i11.Future<List<Map<String, dynamic>>>);

  @override
  _i11.Future<int> update(
    String? table,
    Map<String, dynamic>? data, {
    String? where,
    List<Object?>? whereArgs,
    _i10.ConflictAlgorithm? conflictAlgorithm,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #update,
              [table, data],
              {
                #where: where,
                #whereArgs: whereArgs,
                #conflictAlgorithm: conflictAlgorithm,
              },
            ),
            returnValue: _i11.Future<int>.value(0),
          )
          as _i11.Future<int>);

  @override
  _i11.Future<int> delete(
    String? table, {
    String? where,
    List<Object?>? whereArgs,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #delete,
              [table],
              {#where: where, #whereArgs: whereArgs},
            ),
            returnValue: _i11.Future<int>.value(0),
          )
          as _i11.Future<int>);

  @override
  _i11.Future<T> transaction<T>(
    _i11.Future<T> Function(_i10.Transaction)? action,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#transaction, [action]),
            returnValue:
                _i13.ifNotNull(
                  _i13.dummyValueOrNull<T>(
                    this,
                    Invocation.method(#transaction, [action]),
                  ),
                  (T v) => _i11.Future<T>.value(v),
                ) ??
                _FakeFuture_9<T>(
                  this,
                  Invocation.method(#transaction, [action]),
                ),
          )
          as _i11.Future<T>);

  @override
  _i11.Future<void> execute(String? sql, [List<Object?>? arguments]) =>
      (super.noSuchMethod(
            Invocation.method(#execute, [sql, arguments]),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);
}
